householdData<-read.table("Exploratory Data Analysis/household_power_consumption.txt",head=TRUE,sep=";",na.strings="?",stringsAsFactors=FALSE)
householdData$DateTime<-paste(householdData$Date,householdData$Time)
householdData$DateTime<-strptime(householdData$DateTime,format="%d/%m/%Y %H:%M:%S")
householdData$Date<-as.Date(householdData$DateTime)
plotData<-householdData[which(householdData$Date=="2007-02-01" | householdData$Date=="2007-02-02"),]
png(file="plot4.png",width=480,height=480,units="px")
par(mfrow=c(2,2),mar=c(4,4,2,1))
plot(plotData$DateTime,plotData$Global_active_power,pch=".",type="o",ylab="Global Active Power",xlab="")
plot(plotData$DateTime,plotData$Voltage,pch=".",type="o",ylab="Voltage",xlab="datetime")
with(plotData,plot(DateTime,Sub_metering_1,pch=".",type="o",ylab="Energy Sub Metering",xlab=""))
with(plotData,points(DateTime,Sub_metering_2,pch=".",type="o",col="red"))
with(plotData,points(DateTime,Sub_metering_3,pch=".",type="o",col="blue"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,lwd=1,bty="n")
plot(plotData$DateTime,plotData$Global_reactive_power,pch=".",type="o",ylab="Global_reactive_power",xlab="datetime")
dev.off()